### ISSUE TITLE
Restarting runs for an Unstructured Grid not working

### ISSUE THREAD

**Issue by himakarganti** [code-mphi/ECOGEN#12]
I tried to restart a simulation on an Unstructured Grid and it doesnot run and exits before the first time-step. Can we restart simulations on unstructured grids for Ecogen runs?

**Comment by JorisCaze** [comment]
Dear @himakarganti 

Yes this feature is perfectly working. If you would like to find more info about it, see [documentation](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap4_3restartRun.html).

Be careful to keep the same number of cores as before and specify the right file number to restart to.
