### ISSUE TITLE
How to install ECOGEN on HPC servers

### ISSUE THREAD

**Issue by syam-s** [code-mphi/ECOGEN#14]
Dear Admin,
I am trying to install ECOGEN on an HPC server. When I tried to install using the instructions given in the documentation file, many issues have appeared and I could not found any solution to the problem yet. Any help on this issue is highly appreciated. Thank you.

**Comment by JorisCaze** [comment]
Dear Syam, 

There should not be any issue to install ECOGEN on a HPC server.

Open-MPI and C++ compiler should already be installed, thus it is only required to download and compile ECOGEN with the Makefile. 

Some adjustements might be required in the Makefile to specify the correct path to these libraries. 

Without further description of the problem, it will not be possible for us to give you additionnal help.

Good continuation

**Comment by syam-s** [comment]
Dear Admin,
Thank you for your immediate response and support. Yes, there was some issue with Open-MPI. However, I was not able to find it. I reported the issue to my HPC server admin and he resolved the issue (even he took two days to find the issue and resolve it). I am pasting the communications from my HPC server admin here, I think it may helpful for you in improving ECOGEN for the compilation and execution in HPC servers or others who face similar issues. Thank you.

Communication: 1
--------------------------
          Dear User,
          Issue has been resolved. Please submit interactively or Submit via script.
          cd /home/syam/ECOGEN-2.0
          mpirun -np 8 /home/syam/ECOGEN-2.0/ECOGEN -inp
          /home/syam/ECOGEN-2.0/ECOGEN.xml
          OR
          cd /home/syam/ECOGEN-2.0
          sbatch ecogen_submit.sh
          Output for your Ref. /home/syam/ECOGEN-2.0/job.318639.out
          Thanks..!!

Communication: 2
--------------------------
          Dear user,
          There appears to has some issue while using OpenMPI on PS. Please use Intel MPI and recompile your software.
          1. Load the following modules
          module load compiler/intel-mpi/mpi-2018.2.199
          module load compiler/intel/2018.5.274
          2. Edit Makefile and replace 'mpicxx' with 'mpiicpc' (so that it uses icpc intel compiler)
          3. Compile: make -j 10
          4. For checking, in the submit script, use ./ECOGEN in place of ECOGEN, as follows:
          
          #!/bin/sh
          #SBATCH -N1
          #SBATCH --ntasks-per-node=2
          #SBATCH --time=00:05:00
          #SBATCH --job-name=ECOGEN_test
          #SBATCH --error=job.%J.err
          #SBATCH --output=job.%J.out
          #SBATCH --partition=standard
          cd $SLURM_SUBMIT_DIR
          module load compiler/intel-mpi/mpi-2018.2.199
          module load compiler/intel/2018.5.274
          mpirun -np 2 ./ECOGEN

          It should work now.

**Comment by JorisCaze** [comment]
Dear syam-s, 

Thank you for your feedback. 
Since this issue is not related to ECOGEN, no further "fix" will be provided. 

Best regards, 
Joris
