### ISSUE TITLE
Unable to Run 'Kapila' case from ECOGEN 2 version

### ISSUE THREAD

**Issue by himakarganti** [code-mphi/ECOGEN#16]
I created a test case in ECOGEN 2 that ran successfully using the 'Kapila' model for 2 phases with an unstructued mesh. I tried to run the same in ECOGEN 3.1 by modifying the modelV4.xml file as follows

```
<?xml version = "1.0" encoding = "UTF-8" standalone = "yes"?>
<model>
 <flowModel name="PressureVelocityEq " numberPhases="2" alphaNull="false"/>
 <EOS name="IG_air.xml"/>
 <EOS name="SG_water300K.xml"/>
 <additionalPhysic type="viscosity"/>
</model>
```

I am now getting the following error:
```
-------------------------------------------------
Exception on XML file: this portion of code is under development
****************************************
 XML file concerned: '././libTests/myRuns/liquidInject/modelV4.xml'
 infos on exception in code source :
  file: 'src/InputOutput/Input.cpp'
  line: 620
--------------------------------------------------
```
and ECOGEN causes Segmentation faults. Can someone please help me with Kapila model for ECOGEN 3.1?

**Comment by kevinschmidmayer** [comment]
Hi,

I don't know if this is the only issue but there is a additional space at the end of the model name that should not be there: "PressureVelocityEq " -> "PressureVelocityEq".

Let us know if it does fix your issue.

Best,
Kevin

**Comment by himakarganti** [comment]
That fixed the issue. It is now running now. 

Thanks Kevin,
