### ISSUE TITLE
Structure of initialConditionsVX.xml file for surface tension

### ISSUE THREAD

**Issue by amantr17** [code-mphi/ECOGEN#17]
Dear All,
Please help me out in following coding stuff. I want to create a code which includes injection and outflow Boundary conditions along with two wall conditions. In this case, I need to use the Equation of state having surface tension (SG_liquidForSurfaceTensionCases.xml). i made an attempt to write such code but it shows following error: 

Exception during reading XML file: file not found or incorrect structure
****************************************
 XML file concerned: '././libTests/myTests/BubbleinWater/initialConditionsV4.xml'
 infos on exception in code source :
  file: 'src/InputOutput/Input.cpp'
  line: 861
--------------------------------------------------
Segmentation fault (core dumped)

Kindly suggest me the changes which I need to do.

Thanks & Regards.
Aman Tripathi
Ph.D. Scholar,
IISER Bhopal, India

[modelV4.txt](https://github.com/code-mphi/ECOGEN/files/8104444/modelV4.txt)
[meshV5.txt](https://github.com/code-mphi/ECOGEN/files/8104445/meshV5.txt)
[mainV5.txt](https://github.com/code-mphi/ECOGEN/files/8104446/mainV5.txt)
[initialConditionsV4.txt](https://github.com/code-mphi/ECOGEN/files/8104447/initialConditionsV4.txt)

**Comment by JorisCaze** [comment]
Dear @amantr17, 

The *initialConditions* XML file you provided does not respect the file architecture:
- the injection boundary condition must have a transport node for the color function
- the outflow boundary condition had the node *dataOutflow* closed too early (see the attached file).

Also be aware that the input files must have the *.xml* extension and not *.txt* (although I suspect it was only changed to upload the files to GitHub).

Please find the corrected files attached.

[inputFiles.zip](https://github.com/code-mphi/ECOGEN/files/8108388/inputFiles.zip)

**Comment by amantr17** [comment]
Thank you so much @JorisCaze JorisCaze.
Yes i have converted .xml to .txt only for uploading purpose.

**Comment by amantr17** [comment]
Hello,
In same problem, if we use any geometry from libMeshes by changing only the meshV5.xml, then the following error comes after running some iterations:

Segmentation fault (core dumped)

I think either i have used incorrect value of CFL or totalTime & TimeFreq, or there is some other mistake. 
Note: Clock time taken in this case is very less . Even, 100 iterations run within few seconds & then code shows error.
[inputFiles_nozzle_geo.zip](https://github.com/code-mphi/ECOGEN/files/8113941/inputFiles_nozzle_geo.zip)

Thanks & Regards.
Aman
[inputFiles_nozzle_geo.zip](https://github.com/code-mphi/ECOGEN/files/8113943/inputFiles_nozzle_geo.zip)
