### ISSUE TITLE
Automatic Pressure values at Inlet and Outlet

### ISSUE THREAD

**Issue by amantr17** [code-mphi/ECOGEN#19]
Dear All,
Please help me out in following coding stuff. I am working on problem - flow of air bubble inside water.In coding by ECOGEN, I need to put the Neumann boundary condition instead of Dirichlet boundary condition, such that while taking the Boundary condition as Injection (inlet) and outflow(outlet), I don't want to give the value of inlet pressure and outlet pressure manually, I want that these pressures will be taken automatically. Please suggest the changes in code. 

[mixture_model3.zip](https://github.com/code-mphi/ECOGEN/files/8706393/mixture_model3.zip)
`

Thanks & Regards.
Aman Tripathi

Ph.D. Scholar,
IISER Bhopal, India

**Comment by JorisCaze** [comment]
Dear @amantr17, 

In compressible flows, the state at a boundary condition is defined according to the wave structure of the Riemann problem. Therefore, the choice of a boundary condition must be defined **carefully**. 

I am not sure to understand exactly your problem but I would suggest either to use large enough domain with outflow boundary conditions set to the free-stream pressure or to use non-reflecting boundary conditions to let the waves go out of the domain. 
For more information on boundary conditions see this [page](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_4initialConditions.html#boundary-conditions) of the documentation.

From a quick look at your input files, be aware that 2nd order numerical scheme is not currently available for unstructured meshes, for more information about the compatibility of features within ECOGEN see this [page](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_4featuresModels.html) of the documentation.

**Comment by amantr17** [comment]
Dear Joris,

Is it possible to give Neumann Boundary condition instead of Dirichlet boundary condition for pressure at the inlet along with the injection Boundary condition?

Thanks & Regards.
Aman

**Comment by JorisCaze** [comment]
Dear @amantr17, 

To my knowledge, it is not possible to set mass flow rate and pressure at inlet for compressible flows. 
I mean it can be written but this choice of boundary condition might lead to unphysical behavior depending on the others boundary conditions.

**Comment by kevinschmidmayer** [comment]
No following so I close the issue.
