### ISSUE TITLE
Unstructured Grid In parallel

### ISSUE THREAD

**Issue by jredding375** [code-mphi/ECOGEN#2]
I have one issue occuring when trying to run the test case
 "kapila2DnozzlesInjection". I generate a mesh in gmsh 3.0.6 using command
"gmsh -2 nozzle2D.geo -format msh2"  - no errors are output from gmsh for this command. However, once I attempt to run in parallel, I get a segmentation fault listed below.

************************************************************
          EXECUTION OF THE TEST CASE NUMBER : 1
************************************************************
T1 | Test case : ./libTests/referenceTestCases/kapila/2D/nozzles/injection/
T1 | Number of CPU : 10
------------------------------------------------------
 0) MESH FILE PRETRAITEMENT nozzles/nozzle2D.msh IN PROGRESS...
  1/Mesh nodes reading ...OK
  2/1D/2D/3D elements reading ...OK
  -----------------------------------
    MESH GENERAL INFORMATIONS :
  -----------------------------------
    mesh nodes number : 4397
    elements number : 5110
  3/Attributing nodes to CPUs ...
    0% ... 
[apollo:31485] *** Process received signal ***
[apollo:31485] Signal: Segmentation fault (11)
[apollo:31485] Signal code: Address not mapped (1)
[apollo:31485] Failing at address: 0xb7cb1c128
[apollo:31485] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x354b0)[0x7f56ca5804b0]
[apollo:31485] [ 1] ECOGEN[0x46dbf6]
[apollo:31485] [ 2] ECOGEN[0x46fb45]
[apollo:31485] [ 3] ECOGEN[0x40a92c]
[apollo:31485] [ 4] ECOGEN[0x406732]
[apollo:31485] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f56ca56b830]
[apollo:31485] [ 6] ECOGEN[0x408389]
[apollo:31485] *** End of error message ***

Am I using the correct command format to generate the mesh? I am using the Unstructured grid, and haven't changed anything from the original test case files. 

Thank you.

**Comment by code-mphi** [comment]
Dear jredding375,

It seems that you launch ECOGEN on 10 CPU on a single CPU mesh file. You have to proceed to mesh partition using Gmsh before.
Or simply use ECOGEN on a single CPU.

Whatever, this test case kapila2D/nozzles/injection seems to be out of date in this version.

BR
