### ISSUE TITLE
Cartesian mesh

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#20]
Dear all,

I am an inexperienced college student learning ECOGEN software for a project. For simulating a 3D near-wall bubble collapse, I am trying to mesh a 1mm * 2mm * 2mm cubical domain with a highly refined 0.6mm * 0.6mm * 0.6mm cubical region adjacent to one of the domain's face centres. It involves stretching the mesh along both positive directions. I tried using the meshV5.xml attached with this issue.
[meshV5.txt](https://github.com/code-mphi/ECOGEN/files/9035216/meshV5.txt)
Unfortunately, I am getting the following error: "Exception on XML file: error on stretching definition." My idea was to stretch the mesh along all 5 directions from the smaller cubical region by a factor of 1.01. Is it possible in ECOGEN? If yes what edits should I make in the above code? Or should it be rewritten completely?

Thanking you in advance

Niranjan K. Sabu

**Comment by kevinschmidmayer** [comment]
Hi Niranjan,

I don't know if this is the only issue but at least with a quick look I can see that you didn't specify the stretching from the origin (0 in each direction) to the full length domain. Meaning you have to specify it only in the increasing length direction. Hence, if you first want to decrease the cell size, you simply have to use a factor lower than 1. In your case, 1./1.01 = 0.9900990099.

Hope this fixes your issue.

Best regards,
Kevin Schmidmayer

**Comment by NiruBhai** [comment]
Hello Kevin,

I did some stretching in the decreasing length direction, maybe that is the issue. I will check it out. Thank you!

Niranjan K. Sabu

**Comment by NiruBhai** [comment]
It's working now, thanks!
