### ISSUE TITLE
Axisymmetry

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#21]
Hello everyone,

I am looking towards implementing axisymmetry in a bubble collapse problem to reduce it to a 2D simulation. I saw that there are some test cases already available on the same but everywhere, only the term "symmetry" is being used in the initialconditions.xml file. I am not able to distinguish between axisymmetric cases and planar cases, and in some cases, is confused whether this symmetry refers to mere reflection about a side/face only. I asked about this to a senior friend of mine but even he was helpless. Please help me.

Thanking you in advance,

Niranjan K. Sabu

**Comment by kevinschmidmayer** [comment]
Hi Niranjan,

You simply need to differentiate what is linked to the initial and boundary conditions and what is linked to the model. Axi-symmetry has nothing to do with the former but is solely linked to the modeling since it is related to the system of equations you are solving, i.e. you will find this specification within the model.xml file.

Best regards,
Kevin

**Comment by NiruBhai** [comment]
Dear Kevin,

I saw that there exists "spherical" and "cylindrical" conditions. I think the "cylindrical" one refers to the axisymmetric condition. Am I right? Is the [test case](https://github.com/code-mphi/ECOGEN/blob/devel/libTests/referenceTestCases/UEq/2D/nonSphericalCollapseNearWall/modelV4.xml) given for near-wall non-spherical bubble collapse in ECOGEN axisymmetric?

**Comment by kevinschmidmayer** [comment]
1. I am not sure to understand what you mean by "condition". There are spherical and cylindrical axi-symmetries referring to two different systems of equations. The spherical axi-symmetry is used for 1D simulations with spherical axi-symmetry and the cylindral axi-symmetry is used for 2D simulations with cylindrical axi-symmetry. Does that answer your question?

2. Yes, this test case simulates near-wall non-spherical bubble collapse with axi-symmetry to model a 3D bubble in 2D.

**Comment by NiruBhai** [comment]
Oh, I understand it now. Thank you!
