### ISSUE TITLE
Availability of test case

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#22]
Dear all,

I am learning about bubble collapse near walls. I came across a JFM [article](https://scholar.google.de/citations?view_op=view_citation&hl=de&user=DJEkD6kAAAAJ&sortby=pubdate&citation_for_view=DJEkD6kAAAAJ:d1gkVwhDpl0C) by Dr. Trummler. Out of the various crevice geometries tested, is any case directly available among ECOGEN examples, either among the official documentation or somewhere else?

Thanking you
Yours sincerely

Niranjan K. Sabu

**Comment by kevinschmidmayer** [comment]
Treated elsewhere.
