### ISSUE TITLE
Recombination of VTK files

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#24]
Dear all,

Is there a way to recombine VTK files associated with multiple cores to produce a single VTK file for a given time-step using ECOGEN itself ? If not is there any other way?

Regards,
Niranjan K. Sabu

**Comment by kevinschmidmayer** [comment]
Hi Niranjan,

Parallel output is still on our to-do list since we didn't find the time yet to implement this feature.
So far, I don't know a tool combining the VTK files. Sorry for that.

Best regards,
Kevin
