### ISSUE TITLE
Handling output files

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#25]
Dear all,

Greetings. I use Paraview to visualise the data generated by ECOGEN simulations. While doing even coarse 3D simulations, I am finding it difficult to handle the data as even for 20 timestamps, the total folder size comes out to be 18.7 GB. It is taking a huge amount of time to load each timestep and for finer meshes, the software simply crashes. Is there any way to overcome this issue?

Regards,
Niranjan K. Sabu

**Comment by kevinschmidmayer** [comment]
Hi Niranjan,

This has nothing special to do with ECOGEN. The only thing you could do with ECOGEN is to reduce the output data:

- Reduce the precision of the output in the mainV5.xml file: `<outputMode format="XML" binary="false" precision="4"/>`
- Have the reduced output activated if this is available and you don't need all the information: `<outputMode format="XML" binary="false" precision="4" reducedOutput="true"/>`

Best,
Kevin

**Comment by NiruBhai** [comment]
Thank you @kevinschmidmayer 

Regards,

Niranjan
