### ISSUE TITLE
Is ECOGEN Able to Simulate Non-Newtonian Fluids?

### ISSUE THREAD

**Issue by MGYBY** [code-mphi/ECOGEN#27]
Hello all,

I am new to ECOGEN and found this project really amazing. I have a question for ECOGEN based on my application: can ECOGEN simulate Non-Newtonian multiphase flows? It seems that the rheology models are not included in the source code.

Thank you in advance.

YBY

**Comment by JorisCaze** [comment]
Dear @MGYBY, 

No currently ECOGEN is not able to simulate non-Newtonian multiphase flows. 

Unfortunately, there are no plans to develop this feature in the near future, but if you are interested in doing it yourself, you can open a pull request and we will be happy to accept it after review. 

Best regards,
Joris

**Comment by MGYBY** [comment]
Hello @JorisCaze,

Thank you for your explanation and suggestion. And I also appreciate the development team's effort for the maintenance of ECOGEN.

YBY

**Comment by kevinschmidmayer** [comment]
Hi YBY,

Thank you for your message!
I close the issue. If needed you can re-open it.

Best regards,
Kevin
