### ISSUE TITLE
New Person in CFD Simulation

### ISSUE THREAD

**Issue by FLUIDDYNAMICSM** [code-mphi/ECOGEN#30]
Hi Kevin,

I installed the latest and an older version of ECOGEN on WSL/Windows. 
Thanks for your hard work. The code works great. Just, I do not know why all examples using mesh (unstructured) does not work on my system. I get typical following error. Pls, if you have time, let me know your opinion. 

Thanks a lot.

------------------------------------------------------------------------------

T1 | Test case: ./libTests/referenceTestCases/euler/2D/HPUnstructured/
------------------------------------------------------
 A) READING MESH FILE EXTENSION : square/square.msh
--------------------------------------------------
Exception sur lecture file XML : file introuvable ou structure incorrecte
****************************************
 file XML concerne : 'mesh file not found : ./libMeshes/square/square.msh'
 infos sur exception code source :
  file : 'src/Meshes/MeshUnStruct/MUSGmsh/MUSGmsh.cpp'
  ligne : 54

------------------------------------------------------------------------------

**Comment by NiruBhai** [comment]
Hello @FLUIDDYNAMICSM 

If I remember correctly, only the .geo files are present initially in libMeshes. Mesh them using Gmsh, it should work after that.

Regards,
Niranjan

**Comment by kevinschmidmayer** [comment]
Hi,

@NiruBhai Thank you. You are right.

@FLUIDDYNAMICSM Thank you for your message. Please find additional information in the documentation: https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_3mesh.html#sec-input-unstructured

Best regards,
Kevin
