### ISSUE TITLE
Running multiple parallel jobs at once

### ISSUE THREAD

**Issue by jr144393** [code-mphi/ECOGEN#31]
In the ECOGEN main folder, cases can be defined in ECOGEN.xml and this file is referred to when running the script for a parallel run. Is it possible to run multiple parallel cases at once without creating multiple instances of the ECOGEN folder? 

It is my understanding that if I defined multiple paths within one ECOGEN.xml file, then ECOGEN will run these cases one after another.

**Comment by kevinschmidmayer** [comment]
Hello,

Indeed, ECOGEN is not adapted for your request. You would need to do an extra script to do so, in bash or python for example.

Best,
Kevin

**Comment by tripatmn** [comment]
Hello,

I was facing a similar issue. I installed two instances of Ecogen in two different directories and ran two different simulations together. However, both simulations, while running together are running very slowly. The cases running at the moment have been run before, individually and have run must faster at the time. Do different instances of ecogen share the resources? or why does it slow down ?

Thank you

**Comment by kevinschmidmayer** [comment]
Hi,

One instance of ECOGEN takes the whole power of the CPU cores you asked for, similarly to any software. If you run two instances, resources of your CPU are shared between the instances, again similarly to any software. If other CPU cores were not used, the different instances won't slow down. If you were already using everything, it will. Basic management of resources from your OS.

Best,
Kevin
