### ISSUE TITLE
Cavitation flow around a body

### ISSUE THREAD

**Issue by TwoPhaseLinearStability** [code-mphi/ECOGEN#34]
Hello all,

I am doing a research on cavitation flow. The solver ECOGEN is a good solver. Thank you! 

My simulation issue is a break down when inflow is high enough or ambient pressure is low enough(The 2nd and 3rd figures below are my results which the configuration files are modified on the basis of foil cavitation files in test cases). The minimal pressure is very low compared with saturated vapor pressure. I read the paper by Saurel et al., and they said mass transfer is necessary(marked in green in the first figure below in this e-mail). But I don't know how to add mass transfer into the model. Sorry for my poor knowledge about it. Thanks for your help in advance,

Cheers
![Screenshot_20230307_194450](https://user-images.githubusercontent.com/59474639/223415656-51a45a2b-451c-456a-a77d-33d04ffc09e5.png)
![Screenshot_20230307_090845](https://user-images.githubusercontent.com/59474639/223415672-d43bd744-6142-48b2-bf01-018cedbf31f7.png)
![Screenshot_20230307_090917](https://user-images.githubusercontent.com/59474639/223415681-afe19c23-9c81-4055-8c39-9421b8cf4e89.png)

**Comment by JorisCaze** [comment]
Hello @SmallPang411315, 

Currently, mass transfer is already implemented in **ECOGEN** through a relaxation process using a method similar to the one described in the article you refer to.
More information on this topic is also available in the appendix of [Schmidmayer et al. (2020)](https://doi.org/10.1016/j.cpc.2019.107093) or in [Le Métayer et al. (2013)](https://doi.org/10.1051/proc/201340007).

To use it, the following node must be added to the *modelVX.xml* file:

```xml
<relaxation type="PTMu">
  <dataPTMu liquid="SG_waterLiq.xml" vapor="IG_waterVap.xml"/>
</relaxation>
```

An example of use can be found in the test case [/libTests/referenceTestCases/PUEq/2D/foil/cavitation/](https://github.com/code-mphi/ECOGEN/tree/devel/libTests/referenceTestCases/PUEq/2D/foil/cavitation).

**Comment by TwoPhaseLinearStability** [comment]
Thanks!
