### ISSUE TITLE
Can I give a injection boundary condition at specific part of boundary line or surface? 

### ISSUE THREAD

**Issue by TwoPhaseLinearStability** [code-mphi/ECOGEN#36]
Hello,

Is there possible to state a injection boundary condition at specific part of boundary line or surface?

**Comment by JorisCaze** [comment]
Dear @SmallPang411315, 

Relevant information on boundary conditions can be found in this section of the [documentation](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_4initialConditions.html#boundary-conditions).

In summary, the boundary conditions must be specified according to your mesh type:
- For cartesian/AMR mesh, boundary conditions can only be applied to an entire side of the geometry.
- For an unstructured mesh, you can define a boundary condition on a specific region of the geometry using a physical label defined in the mesh file.

Best regards, 
Joris

**Comment by TwoPhaseLinearStability** [comment]
Thank you. Currently, the 2nd order scheme is only valid on cartesian/AMR mesh, so an ambiguous interface is often seen on unstructured mesh if a complex geometry is involved. Is there any possibility to get a clear interface if a crevice, bump or any other thing is in computational domain? Thank you!

**Comment by kevinschmidmayer** [comment]
Hi,

The only solutions I think about are to increase the order of the scheme (not possible yet for unstructured meshes) or to improve the quality of your mesh, which most of the time is not an easy task to do but unfortunately matters a lot. Note that those remarks are not specific to ECOGEN but are valid for any unstructured solver.

Best,
Kevin
