### ISSUE TITLE
The setup of axisymmetric flow and possibility of separated domain for ARM

### ISSUE THREAD

**Issue by wkholy** [code-mphi/ECOGEN#38]
**Describe the bug**
Dear Developer of ECOGEN,

Thanks for sharing the source code and detailed tutorial files. I am working on a case for a nozzle with perfect gas emission into the water. I am trying to setup an axisymmetric case. May I ask is it enough to set the axis boundary as symmetry one for the axisymmetric case or I should also include a disc-like setup in sphericalCollapse case?
            <dataDisc axis1="x" axis2="y" radius="1.e-4">
                <center x="0." y="0." z="0."/>
            </dataDisc>
In the tutorial, is the nozzle case in /ECOGEN/tree/devel/libTests/referenceTestCases/PUEq/2D/nozzles/tank/ essentially 2-D or axisymmetric?

I found the ARM is pretty useful in cartesian mesh. Is it possilble to mesh two domains, one for unstructured mesh, and one for ARM of cartesian mesh or I could program a nozzle shape in a cartesian domain?

Thanks for your time and effort.

Best regards

Wei

**Comment by NiruBhai** [comment]
Dear Wei,

Please check issue #21 where I had a similar doubt clarified by Kevin as far as symmetry is concerned.

**Comment by kevinschmidmayer** [comment]
Dear Wei,

As @NiruBhai said, you can find answers reading #21. Thank you by the way, Niranjan, for responding.

Regarding coupling Cartesian and unstructured meshes, it is not possible and this feature is not in our plan so far. However, maybe in the future we will adapt AMR for unstructured meshes. Although it is definitely not coming soon.
For the second part of the question, I don't see how you could simulate properly a nozzle with a Cartesian mesh.

Hope it helps.

Best regards,
Kevin

**Comment by wkholy** [comment]
Thanks for the response. @NiruBhai @kevinschmidmayer 
I now understand the setting for axisymmetric case.
