### ISSUE TITLE
Slope limiters

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#39]
Dear all, 

For the PUEqn model, which slope limiter is used, especially for the bubble collapse case? I come across multiple names like THINC, van Leer, MC, etc. when going through papers.

Thanking you,

Niranjan K. Sabu

**Comment by NiruBhai** [comment]
> Dear all,
> 
> For the PUEqn model, which slope limiter is used, especially for the bubble collapse case? I come across multiple names like THINC, van Leer, MC, etc. when going through papers.
> 
> Thanking you,
> 
> Niranjan K. Sabu

I am confused about how to check these details from the existing source code. I also wanted to confirm whether the time integration is a 2-step explicit scheme and whether HLLC is used for solving the Riemann problem at the bubble interface

**Comment by JorisCaze** [comment]
Dear @NiruBhai, 

There are several limiters available with the PUEq model (and also the other flow models). 
For more details, you can find more information about the limiters in this [section of the documentation](https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/Chap3_1_1main.html#global-accuracy-order-of-the-numerical-scheme).

As stated in the documentation you can use a global limiter and optionnally a specific limiter to resolve the flow near the the interface location (such as the THINC limiter) if it is of interest for your test case.

In case you want to check for yourself in the source code, you can find the limiters files in the folder *src/Order2*.

I do not know which papers you are referring to, but the limiter should be chosen according to the physics you are modelling. You have to find a trade-off between the interface diffusion and its shape stability. 

About the numerical scheme, indeed the scheme is explicit. 
It is based on the MUSCL method where a Riemann problem is first solved at half time-step (n+1/2) using extrapolated limited values. From there, the full time-step evolution (n+1) is computed using the previous solution (n) and another Riemann problem using the solution at half time step (n+1/2).
To get a general perspective of this method, you can refer to [Toro's book](https://books.google.fr/books?hl=fr&lr=&id=zkLtCAAAQBAJ&oi=fnd&pg=PR5&ots=SGdCAt3TV4&sig=IhdOC3nFGjmjUc8mVImD8PIv6O0&redir_esc=y#v=onepage&q&f=false) and if you want to understand its specific implementation in ECOGEN you can refer to this [paper](https://doi.org/10.1016/j.cpc.2019.107093).

The HLLC solver is used everywhere in the flow field, except at the boundary conditions that require a specific description using a half-Riemann problem.
If you want to see in more detail the HLLC solver for the PUEq model, you can check its source code [here](https://github.com/code-mphi/ECOGEN/blob/dd550d15f761592e163a99e07e16b691d06302ba/src/Models/UEq/ModUEq.cpp#L100).

**Comment by NiruBhai** [comment]
Thank you @JorisCaze! I am only modifying the boundary conditions of an existing test case so it should be fine using the default settings.

Regards

Niranjan K. Sabu
