### ISSUE TITLE
Output data only for a part of the domain

### ISSUE THREAD

**Issue by NiruBhai** [code-mphi/ECOGEN#41]
Dear all,

I am searching a way to extract the data of only a part of the computational domain (being large) and post-process. It seems that the "cuts" markup is for the same, but I am not able to understand how to implement it from the existing code. Could someone please help? Even extracting a plane section is okay.

Also, an unrelated question: Can ECOGEN be used to simulate bubble chains? 

Regards,
Niranjan

**Comment by kevinschmidmayer** [comment]
Dear Niranjan,

Indeed you should be able to use the 2D cut option to extract a section of your 3D domain. Although I'm almost never using this option, it should be quit easy to set up using the indication from the manualMainV5.xml file. I copy/paste it below:

b) 2D output cut
Possibility to extract 2D output cuts from 3D computations. Define a plane using a vertex and normal vector.
Cut results will be placed in the corresponding results folder under GNU format.
```
<cut2D>
  <vertex x="0.51" y="0.51" z="0.51"/>
  <vecNormal x="1" y="0" z="0"/>
</cut2D>
```

Please let us know if this works.

However, note that 3D data will still be written anyway. If you wish to not write the 3D data, let us know and we will tell you which lines to comment in the code (no option for this).

Regarding your unrelated question, can you elaborate on what you call "bubble chains"?

Best regards,
Kevin

**Comment by NiruBhai** [comment]
Thank you @kevinschmidmayer ! I will check it out. It's fine regarding the bubble chain, it is manageable.

Regards, 
Niranjan
