### ISSUE TITLE
Help Needed for ECOGEN-3.1 Post-Processing Error

### ISSUE THREAD

**Issue by NithinKrishnanS** [code-mphi/ECOGEN#42]
Dear Sir,

I am writing to seek your expertise and assistance in resolving an error that I've encountered during the post-processing of the default Computational Fluid Dynamics (CFD) problem of Shock-Bubble Interaction in 2D using ECOGEN-3.1 solver and post-processing in both ParaView as well as VisIT software.

I am working on the CFD problem and have successfully completed the simulation using ECOGEN-3.1, Pressure and Velocity Equilibrium Model. However, when I attempted to analyze and visualize the results of Vorticity and Baroclinic Vorticity, I encountered an error that I have been unable to resolve. This issue is hindering my progress and preventing me from moving forward with my analysis. Moreover I am also interested in knowing about how to modify the existing code so that I can incorporate the equations of Reynolds Stress, Turbulent Heat flux, Time Averaging and Favre Averaging so that I can explore more on these areas too.

Given your extensive experience in CFD and post-processing, I believe you might be able to help me identify the root cause of this error and provide guidance on how to resolve it. Your insights and expertise would be invaluable in helping me overcome this obstacle and ensure the success of my research work.

Thanks and Regards,

Nithin Krishnan S

**Comment by tripatmn** [comment]
Hi,

I am facing the same issue, were you able to find a work around?

Thanks

**Comment by kevinschmidmayer** [comment]
This issue has been solved by email exchanges. Regarding vorticity visualization, please find below tips for Paraview.

**Paraview**
Here are described tips for ParaView, especially when dealing with filters. ParaView 5.6.0 was used.

In the following, the order of the filters are important.

1. For a typical parallel simulation, use the following filters before working on other filters:
   - `Merge Blocks`,
   - `Clean to Grid`.
2. To smooth the results, use 1. and:
   - `Cell Data to Point Data`.
3. To plot contours, use 1., 2. and:
   - `Contour`.
4. To compute the gradient, the divergence, the vorticity or the QCriterion of a variable, use 1., 2. and:
   - `Gradient Of Unstructured DataSet`.
