### ISSUE TITLE
Coupling to other codes with PreCice by TU Munich

### ISSUE THREAD

**Issue by stefano2734** [code-mphi/ECOGEN#45]
Coupling to other codes with PreCice by TU Munich
https://precice.org/

perhaps a possibility for a wide use of this software with other FEM and CFD  Codes like Calculix and more.

APECSS is a new software for cavitation and his acoustics.
https://github.com/polycfd/apecss

Acoular is a software to see sources in measurement.
https://www.acoular.org/

so a coupling can perhaps improve results and workflow here.

**Comment by kevinschmidmayer** [comment]
Dear stefano,

Thank you for sharing your thoughts. Do you have any particular case you would like to solve using this coupling? Or is there any issue? If not, I will close this "issue".

Best,
Kevin
