### ISSUE TITLE
Some doubts for beginners.  And any tips for beginners?

### ISSUE THREAD

**Issue by VaLiuqqq** [code-mphi/ECOGEN#47]
hello,

I am a beginner at Ecogen and would like to use the existing shock-drop program. Where should I find it, please?

I found that in each case in the test folder only four xml files were used to determine the relevant initial conditions. This is different from other open source software. Other open source software requires C++ programming to write program logic and call the corresponding algorithm to simulate, but Ecogen only needs four xml files to simulate.

So how can I modify it for a specific problem? Just by modifying four xml files? Can't I get what I need by modifying common C++ programming logic?

**Comment by kevinschmidmayer** [comment]
Dear @VaLiuqqq,

Indeed, you only need to modify appropriately the XML files. You could eventually code within the sources for very specific initial conditions, but usually you can do almost everything with the current input files. XML files simplify input files.

Please consider reading the XML manuals (within libTests folder) and the documentation which is well furnished: https://code-mphi.github.io/ECOGEN/docs/sphinx_docs/index.html

Best,
Kevin

**Comment by VaLiuqqq** [comment]
Thank for your reply. @kevinschmidmayer 

ECOGEN/libTests/referenceTestCases/UEq/2D/dropletShockInducedCavitation/Mach2_4  
Is this the file for the shock-droplet aerobreakup case?   But this is only a 2D case, and I can't find a folder related to 3D shock-droplet aerobreakup？

Best wishes！

**Comment by kevinschmidmayer** [comment]
No this isn't. This one is for observing cavitation within the droplet impacted by a high-Mach shock wave.
Sorry, we did not upload the shock-droplet aerobreakup case but it should be rather easy to set it up using the PUEq model with surface tension (and viscosity if needed). This should in the end be rather close to the test case of the droplet shock-induced cavitation.
To go from 2D to 3D is just a matter of adapting the mesh and the types of domain used (disc to sphere, for exemple).

Best

**Comment by 9ebrahimi9** [comment]
I am inexperienced in this and I feel extremely anxious... Additionally, my small pen_ises are a source of disappointment in my life.
