### ISSUE TITLE
Unphysical flow field for 3D shock-bubble interaction when lvlMax>2

### ISSUE THREAD

**Issue by EarlFan** [code-mphi/ECOGEN#5]
Hi! I'm using ECOGEN-v2.0, and I find the unphysical result still exists for 3D shock-bubble case when using high refinement level.

The case is 
```
ECOGEN/libTests/referenceTestCases/kapila/3D/shockBubble/heliumAir/
```

if the lvlMax is larger than 2, the flow field will be unphysical after about 40us when the shockwave reaches the upstream pole of the bubble. Attached please find the density flowfield at 42us when lvlMax = 3.

![2020-05-14_18-22-11](https://user-images.githubusercontent.com/24243804/81923418-3a4d2980-9610-11ea-8c9e-4fbfb690e328.jpg)

Please fix this problem. Thanks!

Regards,
Fan E

**Comment by kevinschmidmayer** [comment]
Hi,

It looks like a CFL issue. In this test case, the CFL is at 0.8 which is relatively high for a 3D case. Try to lower it down until you no longer see those unphysical effects.
If they still persist when reaching around 0.2, please get back to us and we will take a closer look at it.

In general, such unphysical effects are coming from a too high CFL. Lower it down is the first thing to try.

Best regards,
Kevin Schmidmayer

**Comment by EarlFan** [comment]
> Hi,
> 
> It looks like a CFL issue. In this test case, the CFL is at 0.8 which is relatively high for a 3D case. Try to lower it down until you no longer see those unphysical effects.
> If they still persist when reaching around 0.2, please get back to us and we will take a closer look at it.
> 
> In general, such unphysical effects are coming from a too high CFL. Lower it down is the first thing to try.
> 
> Best regards,
> Kevin Schmidmayer

Hi,!

Thanks for your help! The CFL problem has came up to me until you point it out. The problem is solved.

Regards,
Fan E
