### ISSUE TITLE
The axisymmetric source term of viscosity.

### ISSUE THREAD

**Issue by EarlFan** [code-mphi/ECOGEN#7]
Dear ECOGEN developers,

Hi!

When reading the axisymmetric source term of viscosity in [APKViscosity.cpp](https://github.com/code-mphi/ECOGEN/blob/devel/src/AdditionalPhysics/Viscosity/APKViscosity.cpp),  it seems the divergence of velocity is not properly evaluated in cylindrical coordiantes. Extra terms related to  

<img src="https://render.githubusercontent.com/render/math?math=v_r/r">

shall be added to the cylindrical source terms. Please refer to [1.2-7](https://www.afs.enea.it/project/neptunius/docs/fluent/html/th/node11.htm) for more details as the equations are not easily rendered on github..

For example, when accounting for this term, the source term of momentum in x direction on line 353

`static_cast<FluxKapila*> (fluxBuff)->m_qdm.setX(muMix * (dvdx + dudy) / r);`

 is

`static_cast<FluxKapila*> (fluxBuff)->m_qdm.setX(muMix * (dvdx + 1.0/3.0 *dudy) / r);`

Since other methods can be performed accounting for the axisymmetric assumption, such as modifying the cellInterface area instead of adding extra source terms, I'm not sure if this is a bug.

Regards,
Fan E

**Comment by kevinschmidmayer** [comment]
Hi,

I am not sure this is a bug either and I would need to look closer at it but first, could you provide us the name of a paper containing the information you are talking about? Then we will access it on our own instead of adding a link.

Thank you in advance,
Kevin

**Comment by EarlFan** [comment]
I think this problem lies in the divergence of velocity in cylindrical coordinate, and many textbooks can be used for reference. The _Principles of combustion_ is the one I can find around

> Table 3.10, equation (A)&(J) show the divergence of velocity 
> Table 3.4 shows the equations of motion for incompressible flow in cylindrical coordinate (r, theta, z)
> -- <cite>Kuo, K. K. (2005). Principles of combustion (No. TJ254. 5 K85 2005).</cite>

simple algebraic manipulation of viscous term in momentum function will show the problem.

Regards,
Fan E

**Comment by EarlFan** [comment]
Hi!

I think Equation(8) in this paper is also helpful.

> Wen, C. Y., Massimi, H. S., & Shen, H. (2018). Extension of CE/SE method to non-equilibrium dissociating flows. Journal of Computational Physics, 356, 240-260.

Regards,
Fan E

**Comment by kevinschmidmayer** [comment]
Hi,

I finally found the time to look at this and thanks for seeing the issue.
The correction is aligned with what you proposed and it also corrects the other terms (when wrong).

Therefore, you will be able to find the corrections in the next release version, hopefully in a few months.

Best regards,
Kevin

**Comment by kevinschmidmayer** [comment]
Hi,

ECOGEN V3.0 is released and contains the previously mentioned corrections.
Please let us know if you observe any other issues.

Best regards,
Kevin
